### ISSUE TITLE
Heads up on using iSTFTNet

### ISSUE THREAD

**Issue by hadware** [mush42/optispeech#11]
Hey there,

Magnificent project, i've spent quite some time looking for a project like this one (ended up finding this via Leanspeech). During my research, i've come upon this thing : https://github.com/rishikksh20/iSTFTNet-pytorch/

From what I gathered, optispeech is using WaveNext as a vocoder. It seems to work really well (in this case, at least). I was wondering if you'd heard about iSTFTNet and if you knew:
- if it performed as well as WaveNext
- if it was more lightweight (in memory & CPU usage) than WaveNext

**Comment by hadware** [comment]
Well, I read the WaveNext paper a bit more carefully (using mighty ctrl-f), and they actually mention iSTFTNet a lot (to say they're performing much better), so that might answer it.

**Comment by mush42** [comment]
Adding to what you've already discovered, ISTFTNet requires an additional `ISTFT` component when you deploy it. You cannot easily export it to ONNX unless you sacrifice some quality, and if you want to use a native `ISTFT` implementation, you must compile it separately and link it to your TTS app.

At least `WaveNeXt` is self-contained.
