### ISSUE TITLE
Status update on Leanspeech

### ISSUE THREAD

**Issue by hadware** [mush42/optispeech#12]
Hey, it's me again. 

I'm making a different issue for a different question : "What's up with leanspeech?".

To clarify: i've seen your leanspeech implementation (both the standalone repo and in optispeech), and I wondered if you'd tested it, and how well it performed. Also, how much "leaner" is it compared to lightspeech.  Finally, it seems that leanspeech isn't capable of doing rate/pitch/energy modulation. Is that correct?

**Comment by mush42** [comment]
@hadware the version of `LeanSpeech` published for the `LIMITS` challenge is not that lightweight. Current `OptiSpeech` implementations are faster, considering that `LeanSpeech` as published is an acoustic model, while `OptiSpeech` is e2e.

I didn't test the leanspeech backbone yet, but it is already slower than other backbones in this repo.
