### ISSUE TITLE
What is the feature os this project?

### ISSUE THREAD

**Issue by JohnHerry** [mush42/optispeech#16]
Hi, thank you for the new job for TTS,  is there any paper to introduce the job? I do not know the idea of this project, is it targeted at to producing speech from text with the same quality like token based LLM-TTS and with fewer clean training data and very fast inference?     or it is a e2e tts more natural then FastSpeech2/VITS like model but can not reach the quality of LLM-TTS? thank you.

**Comment by mush42** [comment]
@JohnHerry this is a new take on the e2e TTS technology using different backbones. The project attempts to optimize for speed and efficiency, targeting on-device use cases.

**Comment by JohnHerry** [comment]
> @JohnHerry this is a new take on the e2e TTS technology using different backbones. The project attempts to optimize for speed and efficiency, targeting on-device use cases.

OK, Thank you for the help.
