### ISSUE TITLE
Training new language

### ISSUE THREAD

**Issue by thewh1teagle** [mush42/optispeech#2]
Hey!
Thanks for sharing this. the repository looks well organized.

I would like to train new language - Hebrew. 
Can you add information in the steps regarding training on new language?

I have 6 hours of wav file in high quality along with their corresponding transcription, diactirized.
Does that sounds enough data for training? do you know how many steps I'll need?
Looks like you trained it on English language, have you tried on another language such as Arabic?

Thanks

**Comment by w11wo** [comment]
Hi @thewh1teagle, I'd like to help out.

I've successfully trained an OptiSpeech model for Indonesian (`id`), as shown here https://github.com/mush42/optispeech/issues/1#issuecomment-2316492228.

It's quite simple to add support for a new language. You mainly just have to add a new text processor (i.e. add language code during phonemization step), and then designate a new training recipe that uses that text processor. Here's an example of my Indonesian recipe https://github.com/bookbot-hive/optispeech/commit/b5b11983fe7e322a39df4a39f9564cf4065dc114.

For my training, I used 43 mins of data (~800 utterances) and trained it for 2M steps (same as default config).

Hope this helps!

**Comment by thewh1teagle** [comment]
@w11wo 
Thanks for your help!

How long does it took for you to train it 2M steps? It sounds a lot. Did you used colab A100 GPU?
I noticed that it used espeak-ng both in pre-processing and inferencing. So I need to make sure that the phonemizer of espeak-ng with Hebrew is good. Hebrew is complex language with many unusual rules...

Are you satisfied with the results, Is it good as the English one here? 



> Here's an example of my Indonesian recipe [bookbot-hive@b5b1198](https://github.com/bookbot-hive/optispeech/commit/b5b11983fe7e322a39df4a39f9564cf4065dc114).

If the audio files I have is 1 speaker and I'll change to rate to be like in the config, should I change some configuration from yours?

**Comment by w11wo** [comment]
Hi @thewh1teagle.

> How long does it took for you to train it 2M steps? It sounds a lot. Did you used colab A100 GPU?

It took me ~3 days. I used a RTX 3090 GPU (my company's local machine).

> I noticed that it used espeak-ng both in pre-processing and inferencing. So I need to make sure that the phonemizer of espeak-ng with Hebrew is good. Hebrew is complex language with many unusual rules...

Yes, definitely. You can also modify the phonemizer backend if needed. I've successfully integrated gruut as my English phonemizer, for instance.

> Are you satisfied with the results, Is it good as the English one here?

I've been using LightSpeech for on-device TTS, and I find OptiSpeech to be much better than LS given its size. It's probably not as good as the English sample, likely because I used a small dataset, but so far I have no issues with it.

> If the audio files I have is 1 speaker and I'll change to rate to be like in the config, should I change some configuration from yours?

My config is also 1 speaker and I've changed the sample rate to 44.1kHz. Feel free to adapt to your setup. If you need to change the rate, you can modify the feature extractor to your desired config.

Good luck!

**Comment by mush42** [comment]
@thewh1teagle

@w11wo did a good job in explaining what's needed.

The model is built from the ground up to support other languages besides English.

If you want to train with a custom text front-end, do the following:

1. Create a custom class in `optispeech.text.tokenizers` that follows the interface of `optispeech.text.tokenizers.BaseTokenizer`. Most likely you need to override the `__call__` method, which accepts the text and the language which can be `None` for unilingual   front ends, and should return integer IDs for the given text.
2. In your dataset config add the following:

```
...
text_processor:
  tokenizer_name: <the name you gave to your custom tokenizer>
```

- Regarding dataset size, I think 6 hours are quite enough.
- Regarding training time, I think it depends on which backbone you use. ConvNeXt is the slowest to train, but it gives nice balance between inference speed and quality, while LightSpeech is fast to train and infer but it's quality is lower than ConvNeXt.
- It took me between 7-10 days to train the ConvNeXt-based model for 500K steps, but stopping at 300K steps gives good quality.
- Note that the default total training steps are 2M, 1M for the generator and 1M for the discriminator. So at the end, the model is only trained for 1M steps.

**Comment by thewh1teagle** [comment]
Thank you all. I'll start soon and check it.

I have 6 hours of high quality audio along with their diacritized transcriptions. My primary concern is the accuracy of espeak-ng. If espeak-ng turns out to be inaccurate, would it be advisable to train on diacritized characters instead? How challenging would it be to fix or improve espeak-ng?

**Comment by mush42** [comment]
FYI, I do have a demo for a trained model for OptiSpeech.

[Find it here](https://optispeech.geotts.ge/)

**Comment by thewh1teagle** [comment]
> If you have an alternative phonemizer you can easily adopt it.

I have added the missing phonemes to my espeak-ng fork, but I noticed that the repository I'm using relies on the Piper phonemizer. How can I provide a metadata file with the phonemes directly?

Additionally, there are many dependencies that don't seem directly related to the training process. I believe the repository could be improved by separating it into multiple packages, similar to Rust crates. For example, one package could focus on preprocessing, another on inference, and so on. This would make it easier to identify the important parts to focus on for training.

I would be happy to contribute to this restructuring once I fully understand the repository. However, I'm unsure if starting training without a deeper understanding is a good idea. I have 3 hours of 22.05 kHz mono audio (2-10 second clips) with corresponding dotted transcriptions and a ready-to-use fork of espeak-ng. I hope that's all I need to get started.

**Comment by thewh1teagle** [comment]
> FYI, I do have a demo for a trained model for OptiSpeech.

Thanks! it sound really good. 
It will be interesting to see how it will be in Hebrew... There is no open model in Hebrew at this level yet and the language is relatively complex

**Comment by mush42** [comment]
@thewh1teagle

- Regarding your eSpeak-ng fork, you can implement a custom class that calls it via a subprocess, or call the lib via ctypes. If you want the punctuation handling of piper-phonemize, you can patch and build it yourself, it is only one Docker command [see build instructions here](https://github.com/rhasspy/piper-phonemize)
- Keeping it simple for now. I created [an inference-only package](https://github.com/mush42/optispeech/tree/main/ospeech/), for training/development use the main package.
- Regarding training, it is only three commands, as long as all custom components are ready.
This is what I do:

1. Preprocess the dataset
```
python -m optispeech.tools.preprocess_dataset \
    <my_dataset_config> \
    <my_dataset_directory> \
    <processed_dataset_directory>
```

2. Generate dataset statistics and update the config with them:
```
python -m optispeech.tools.generate_data_statistics <my_dataset_config>
```

3. Start training:
```
python -m optispeech.train \
    experiment="<my_experiment_config>" \
    model.train_args.evaluate_utmos=false \
    data.batch_size=32 \
    data.num_workers=8 \
    data.train_filelist_path="<processed_dataset_directory>/train.txt" \
    data.valid_filelist_path="<processed_dataset_directory>/val.txt" \
    callbacks.model_checkpoint.every_n_epochs=5  \
    paths.log_dir="<logs_directory>"
```

**Comment by thewh1teagle** [comment]
Thanks. turns out that I can easily use my custom espeak-ng from within piper phonemizer package.

I started to train but it failed with error.
Also looks like the `train.txt` and `val.txt` doesn't have the transcriptions / phonemes. only the path to wav files. is that expected? where it takes the transcription from?


<details>

```console
    self.on_run_start()
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 328, in on_run_start
    call._call_lightning_module_hook(trainer, "on_train_start")
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 167, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/root/home/optispeech/optispeech/model/base_lightning_module.py", line 73, in on_train_start
    if self._opti_reset_optim_and_lr:
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'OptiSpeech' object has no attribute '_opti_reset_optim_and_lr'
[2024-09-07 19:37:35,831][optispeech.utils.generic][INFO] - Output dir: /root/home/optispeech/data/saspeech/logs/train/saspeech_he/runs/2024-09-07_19-37-06
Error executing job with overrides: ['experiment=saspeech-he', 'model.train_args.evaluate_utmos=false', 'data.batch_size=32', 'data.num_workers=8', 'data.train_filelist_path=data/saspeech/train.txt', 'data.valid_filelist_path=data/saspeech/val.txt', 'callbacks.model_checkpoint.every_n_epochs=5', 'paths.log_dir=data/saspeech/logs']
Traceback (most recent call last):
  File "/root/home/optispeech/optispeech/train.py", line 114, in main
    metric_dict, _ = train(cfg)
  File "/root/home/optispeech/optispeech/utils/generic.py", line 88, in wrap
    raise ex
  File "/root/home/optispeech/optispeech/utils/generic.py", line 78, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/root/home/optispeech/optispeech/train.py", line 81, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1025, in _run_stage
    self.fit_loop.run()
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 201, in run
    self.on_run_start()
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 328, in on_run_start
    call._call_lightning_module_hook(trainer, "on_train_start")
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 167, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/root/home/optispeech/optispeech/model/base_lightning_module.py", line 73, in on_train_start
    if self._opti_reset_optim_and_lr:
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'OptiSpeech' object has no attribute '_opti_reset_optim_and_lr'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Training: |                                                                                                                                                                                                              | 0/? [00:01<?, ?it/s]
```

</details> 


This is everything I changed to start train on my dataset:

https://github.com/thewh1teagle/optispeech/commit/2882a5376a63d086794d7eab926fb585cf82b76d

Also, do I need to preprocess again if I got the statistics? or it's used only for the statistics?

**Comment by mush42** [comment]
@thewh1teagle 

- The processed data is stored in json and npz files for text and arrays respectively.
- You don't need to preprocess again, stats are used during training.
-

**Comment by thewh1teagle** [comment]
> * The processed data is stored in json and npz files for text and arrays respectively.

Oh I didn't noticed the json files there. It will be useful if the json will include the phonemes not just their IDs, for easily check that it's correct phonemes

Does the configs I used looks correct? 

This is basically the data I have:

```console
$ ls saspeech/train/wav/ | wc -l
2688

$ ls saspeech/val/wav/ | wc -l
298

$ ffmpeg -i saspeech/train/wav/gold_001_line_128.wav
44100 Hz, mono, s16, 705 kb/s

$ head -n 1 saspeech/train/metadata.csv 
gold_001_line_124|בְּבִנְיָינִים מִסְפָּר 36 וְ-38 בִּרְחוֹב סַרְלִין בְּחוֹלוֹן,

$ head -n 1 saspeech/val/metadata.csv 
gold_000_line_000|שָׁלוֹם, צְלִיל אַבְרָהָם.
```

Also turns out the sample rate of my data is `44100 Hz` but I can't find the config in feature_extractor. 
Should I just copy [48khz.yaml](https://github.com/mush42/optispeech/blob/main/configs/data/feature_extractor/48khz.yaml) into `44khz.yaml` and change only the `sample_rate` to `sample_rate: 44100`?

**Comment by mush42** [comment]
@thewh1teagle  the difference between this and piper is that this is based on JETS not Vits. JETS is considered by many as being better than Vits in quality.
Also you can try gradient accumulation to train with higher effective batch sizes.

**Comment by thewh1teagle** [comment]
@mush42 

I tried even on A100 with 40GB of vram and I got out of memory error with this:

```console
python -m optispeech.train \
    experiment="saspeech-he" \
    model.train_args.evaluate_utmos=false \
    data.batch_size=16 \
    data.num_workers=8 \
    data.train_filelist_path="data/saspeech/train.txt" \
    data.valid_filelist_path="data/saspeech/val.txt" \
    callbacks.model_checkpoint.every_n_epochs=5  \
    paths.log_dir="data/saspeech/logs"
```

I don't think I can get something more powerful than that. what can I do?

```console
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 13.64 GiB. GPU 0 has a total capacity of 39.50 GiB of which 12.78 GiB is free. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 21.59 GiB is allocated by PyTorch, and 4.59 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

Tried also to set this environment vairable `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` but it didn't help.

**Comment by mush42** [comment]
@thewh1teagle 
Please check that your data does not include very long utterances. I faced OOM errors with ljspeech because of that.
Filter out utterances with audio more than 20 seconds of length.
I have successfully trained all models of different architectures with a T4 (16 GB) and Quadro RTX 6000 (48 GB).
A batch-size of 16 always works without giving OOM errors.

**Comment by thewh1teagle** [comment]
> Please check that your data does not include very long utterances. I faced OOM errors with ljspeech because of that.
> Filter out utterances with audio more than 20 seconds of length.

I checked but I don't have wav file with duration longer than 20 seconds.

```python
from pathlib import Path
import librosa

files = [i for i in Path('wavs').glob('*')]

max = 0
for file in files:
    duration = librosa.get_duration(filename=str(file))
    if duration > max:
        max = duration
print(max)
```

My maximum duration is `14.0`

**Comment by w11wo** [comment]
@thewh1teagle, I'm training on 1 x RTX 4090 with 24GB of VRAM. I reduced the batch size to 8, which still trained fine. Perhaps you could try reducing the batch size to 8?

**Comment by thewh1teagle** [comment]
> I'm training on 1 x RTX 4090 with 24GB of VRAM. I reduced the batch size to 8, which still trained fine. Perhaps you could try reducing the batch size to 8?

I think that batch size of 8 worked for me too. but then the training is very slow. it takes few minutes for single epoch, is that expected?

```console
Epoch 0:  27%|█████████████████▋                                               | 367/1344 [00:58<02:35,  6.28it/s
```

**Comment by w11wo** [comment]
@thewh1teagle

Yes, it is expected, my training took 11 mins/epoch

```
Epoch 249: 100%|█| 3927/3927 [11:17<00:00,  5.80it/s
```

You can have a look at the TensorBoard's Audio tab every now and then to see how it sounds on the eval set. I suggest waiting until at least 100k-300k steps to hear how it sounds -- and this shouldn't take too long.

You can modify this value in the config to control how frequently to save the checkpoint:

```yaml
trainer:
  check_val_every_n_epoch: YOUR VALUE HERE
```

**Comment by thewh1teagle** [comment]
@w11wo 

Thanks! 
I'll try tomorrow to keep it train and then I'll check the result at 100k step in tensorboard

**Comment by thewh1teagle** [comment]
I'm on 60k steps. It doesn't sound good, but I can understand it :)
I forgot to config to save the checkpoints, I think that it will save only in 9M step. 
But I noticed that there's checkpoint files in the logs folder, can I use it? @mush42 
I tried to infer it but I got this error:

```console
python3 -m optispeech.infer checkpoint_epoch\=192_step\=128696.ckpt hello output
```

<details>

```console
    return self.method(cls, *args, **kwargs)
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 1582, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/pytorch/core/saving.py", line 63, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/lightning/fabric/utilities/cloud_io.py", line 60, in _load
    return torch.load(
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1097, in load
    return _load(
  File "/root/home/optispeech/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1526, in _load
    del torch._utils._thread_local_state.map_location
AttributeError: map_location
```

</details>

**Comment by mush42** [comment]
@thewh1teagle
I can confirm this issue. I faced it in the past. Let me see what I can do.
I'm open to accept PRs for sure.

**Comment by thewh1teagle** [comment]
> I can confirm this issue. I faced it in the past. Let me see what I can do.

Is there a workaround? I can't continue the training or infer it

**Comment by mush42** [comment]
@thewh1teagle I did a very ugly hack whereby I removed the offending line :D

**Comment by mush42** [comment]
Any way, I'll resolve these versioning issues next weekend.

**Comment by thewh1teagle** [comment]
> I did a very ugly hack whereby I removed the offending line :D

Nice! so the latest code should work fine with that and I can continue from the checkpoint I have?
I can fix the issue with the versioning meanwhile

**Comment by thewh1teagle** [comment]
Thanks so much for the help! After resolving the issue with loading the model by upgrading PyTorch to version 2.3.1, I was finally able to export it to onnx.

The model is currently at 50k training steps, and I tested it on several Hebrew sentences. I'm already impressed! It generates complete sentences in less than 0.1 seconds on a CPU with onnx runtime, and even at this stage, every word is understandable with quite good pronunciation. The only aspect that seems to need improvement is the overall audio quality, which I expect will get better as the training progresses.

Do you think that once I reach 9M steps, I'll be able to fine-tune the model with a new voice to change the speaker?

**Comment by mush42** [comment]
@thewh1teagle good to hear that.

I don't think you need more than 2M steps for training. Even 1M steps are enough imo. Just bare in mind that 1M steps actually means 2M steps (1M for the generator and 1M for the discriminator).

You can always finetune on new speakers. With alignment and duration already taken care of, you will be able to get good results in fewer steps.

**Comment by mush42** [comment]
@thewh1teagle In my training runs, I usually get good quality audio around 350K steps.
Also, when finetuning, I recommend to continue training from the last epoch, don't reset the trainer state. I learned this the hard way :D

**Comment by thewh1teagle** [comment]
Have you encountered the issue where training slows down significantly over time? Initially, an epoch of 168 steps with a batch size of 16 took 38 seconds, but now it takes 2 minutes and 30 seconds for the same epoch.

Interestingly, using a batch size of 16 seems slower than 8. The GPU (RTX 3090) isn’t fully utilized, although its VRAM is, and there’s plenty of available RAM and CPU.

Any insights on why this slowdown happens?

**Comment by mush42** [comment]
@thewh1teagle
Training happens in 2 stages:

1. Acoustic model pretraining: by default the first 1000 steps. The heaviest component (the discriminator) is not trained.
2. E2E training: all of the components are trained together. During this stage the discriminator and it's losses takes most of the time in training.

**Comment by thewh1teagle** [comment]
> 1. Acoustic model pretraining: by default the first 1000 steps.

so maybe that's the problem that it doesn't recognize that I start from pretrained model due to the issue that the training step is not restored?

https://github.com/mush42/optispeech/issues/5

**Comment by mush42** [comment]
@thewh1teagle just remove the `forced_resume` argument.

**Comment by thewh1teagle** [comment]
> @thewh1teagle just remove the `forced_resume` argument.

It happens also without t he forced_resume argument.

**Comment by thewh1teagle** [comment]
> @thewh1teagle just remove the `forced_resume` argument.

Apologies. simply providing the checkpoint wthout forced resume works (I has some patches). thanks!

**Comment by thewh1teagle** [comment]
> * Acoustic model pretraining: by default the first 1000 steps. The heaviest component (the discriminator) is not trained.
> * E2E training: all of the components are trained together. During this stage the discriminator and it's losses takes most of the time in training.

I still believe that the training is slow compared to the possibility. currently it trains like single step per second. (batch_size of 8 on rtx3090)
To reach 500k it will take 6 days at this speed.

**Comment by thewh1teagle** [comment]
Maybe the profiler can tell why it trains so slow

![image](https://github.com/user-attachments/assets/592ac6e8-a33f-4d6a-a5bd-5c9954258354)

**Comment by mush42** [comment]
@thewh1teagle I suspect the alignment module. At least in Matcha-TTS MAS has a lot of overhead.

**Comment by thewh1teagle** [comment]
> I suspect the alignment module. At least in Matcha-TTS MAS has a lot of overhead.

This is literally all I added: https://github.com/thewh1teagle/optispeech/commit/aee021ab7475d37a6954bb8d901e32fc206b1688

And the command I use

```console
python -m optispeech.train \
    experiment="saspeech-he" \
    model.train_args.evaluate_utmos=false \
    data.batch_size=16 \
    data.num_workers=8 \
    data.train_filelist_path="data/saspeech/train.txt" \
    data.valid_filelist_path="data/saspeech/val.txt" \
    callbacks.model_checkpoint.every_n_epochs=5  \
    paths.log_dir="data/saspeech/logs" \
    callbacks.model_checkpoint.save_last=True \
    ckpt_path="last.ckpt"
```

Every step is sloowww... 1 second

@w11wo said that it took for him 3 days for 1M steps. In that case it should be much faster than 1-step/1-second.

**Comment by rmcpantoja** [comment]
Hi,
I believe training speed will also depend a lot on how much speed your GPU has.
Cheers.

**Comment by thewh1teagle** [comment]
> Hi,
> I believe training speed will also depend a lot on how much speed your GPU has.

Hey :)
Of course. I mean that I use the same GPU. Tried with RTX 3090 or RTX 4090Ti. 24 vram / 16 vram.

**Comment by mush42** [comment]
@thewh1teagle can you confirm that the speed up continues to steps beyond 1000?
When it starts from scratch it will train fast for the first 1000 steps then it'll include the discriminator which is going to slow training down.

**Comment by thewh1teagle** [comment]
> @thewh1teagle can you confirm that the speed up continues to steps beyond 1000? When it starts from scratch it will train fast for the first 1000 steps then it'll include the discriminator which is going to slow training down.

You right. the first 1000 steps are fast like 10it/s and then it slow down to 1.42it/s (step per second)
On RTX 3090 with 24vram and batch size of 8. (also tried with 16).
That's too slow. it will take 60 hours to reach 300k steps. 
@w11wo reported that he trained 2M steps in 3 days.

**Comment by mush42** [comment]
@thewh1teagle 
Training speed doesn't only depend on VRAM imo. It also depends on the overall performance of your GPU.
You can remove some of the losses/discriminators, but quality will be degraded.

**Comment by mush42** [comment]
Discriminators operate in the time domain dealing with the raw waveform, whereas the generator operates on a compact representation.

**Comment by thewh1teagle** [comment]
> That's too slow. it will take 60 hours to reach 300k steps.

@mush42 

In that case, that's expected on RTX 3090?
I prefer quality... but didn't thought that I would need to train more than 3 days. I don't have local machine so I use cloud machines

**Comment by thewh1teagle** [comment]
That's how it sounds on `checkpoint_epoch=488_step=262762.ckpt`. the step considered has half?

I don't know if you can notice because it's Hebrew and may sounds weird anyway, but there's some white noise / vibrations.

https://github.com/user-attachments/assets/d361f727-c713-4754-b5dc-9d523d028b93

**Comment by mush42** [comment]
@thewh1teagle
I notice some artifacts.
What pitch extractor are you using?

**Comment by thewh1teagle** [comment]
> What pitch extractor are you using?

Seems like the default one?

I use this `44.10khz` config

`feature_extractor/44.10khz`
```yaml
defaults:
  - default
  - _self_

sample_rate: 44100
n_feats: 80
n_fft: 2048
hop_length: 512
win_length: 2048
f_min: 20
f_max: 11025

```

**Comment by mush42** [comment]
@thewh1teagle would you mind telling me the exact value of the `pitch_extractor` key? I switched the default last week, I don't know if you're using the up-to-date one.

**Comment by thewh1teagle** [comment]
> would you mind telling me the exact value of the `pitch_extractor` key? I switched the default last week, I don't know if you're using the up-to-date one.

Oh I updated the branch from your latest code while resume training. I hope that I started with the same one.

Currently my default.yaml:

<details>

```yaml
_target_: optispeech.dataset.feature_extractors.CommonFeatureExtractor
sample_rate: 24000
n_feats: 80
n_fft: 2048
hop_length: 300
win_length: 1200
f_min: 80
f_max: 8000
center: false
pitch_extractor:
  _target_: optispeech.dataset.feature_extractors.pitch_extractors.EnsemblePitchExtractor
  _partial_: true
  batch_size: 2048
  interpolate: true
preemphasis_filter_coef: null # apply preemphasis filter
lowpass_freq: null
highpass_freq: null
gain_db: null
trim_silence: false
trim_silence_args:
  silence_threshold: 0.2
  silence_samples_per_chunk: 480
  silence_keep_chunks_before: 2
  silence_keep_chunks_after: 2

```

**Comment by mush42** [comment]
@thewh1teagle
Make sure that when you preprocessed your dataset you were using the `EnsemblePitchExtractor, not the JDC one. JDC extractor is very bad and leads to very robotic output. I'm getting impressive results with the Ensemble extractor.

Unfortunately, there is no way other than comparing file dates with commit date.

**Comment by thewh1teagle** [comment]
> Unfortunately, there is no way other than comparing file dates with commit date.

Thanks. I'll check and hope I've used it already.
If not, do I have to start the train from scratch or just preprocess again - create statistics again - and continue training?

**Comment by mush42** [comment]
@thewh1teagle 
Preprocess and resume from last checkpoint.

**Comment by w11wo** [comment]
Hi @thewh1teagle. Just to be clear, for my training to reach 2M steps (which is 1M step for generator, 1M step for discriminator) in ~3 days, I didn't use the default model (Transformer backbone). I used the ConvNext backbone.

Hope this helps.

**Comment by thewh1teagle** [comment]
Thank you @w11wo !
I'll try to compare it with ConvNext since I use the default one.

If you still training or @mush42 I really appreciate if you could look at the output and share here the speed (iteration per second as it/s from the progress bar)

**Comment by mush42** [comment]
@thewh1teagle the numbers you gave are consistent with my experience. Yeah, same numbers.

**Comment by mush42** [comment]
@thewh1teagle regarding memory usage... I faced the same OOM error on one dataset. Whatever I do, seams like I cannot make it train with a batch size of 16. Strange thing it only happens with some datasets not all.

**Comment by thewh1teagle** [comment]
> I faced the same OOM error on one dataset. Whatever I do, seams like I cannot make it train with a batch size of 16. Strange thing it only happens with some datasets not all.

Interesting! what if you change pytorch version like I did? 

```console
rye add torchaudio==2.3.1
```

**Comment by mush42** [comment]
@thewh1teagle did it help you? by how much?

**Comment by thewh1teagle** [comment]
> did it help you? by how much?

I could train with batch size of 16 instead of 8 without OOM. I'm not 100% sure that this worked with 16 thanks to this version downgrade but maybe.

By the way since the batch size didn't changed much the speed I decided to rent cheaper GPU - RTX 3060TI with 8GB ram and I changed batch size to 4. Same speed as with RTX4090 24 vram etc...
I only hope that batch size of 4 is fine to use.

**Comment by thewh1teagle** [comment]
@mush42 

I created this class to improve pronunciation handling and it sounds much better now by adding pauses after `?` / `!` / `\n` etc. what do you think? maybe piper already can handle it somehow?

As for SSML parsing, did you find solution to support it?

<details>

```python
import re
from dataclasses import dataclass

@dataclass
class Segment:
    text: str
    next_pause: float

class SegmentExtractor:
    def __init__(self, default_pause: float = 0.02, question_pause: float = 0.05, period_pause: float = 0.05, new_line_pause = 0.3):
        self.default_pause = default_pause
        self.question_pause = question_pause
        self.period_pause = period_pause
        self.new_line_pause = new_line_pause
    
    def extract_segments(self, text: str):
        segments: list[Segment] = []
        sentences = re.split(r'([.?!:\n])', text)
        for i in range(0, len(sentences) - 1, 2):
            sentence = sentences[i].strip()
            punctuation = sentences[i + 1]
            if sentence:  # Ensure the sentence is not empty
                if punctuation == '.':
                    segments.append(Segment(text=f"{sentence}{punctuation}", next_pause=self.period_pause))
                elif punctuation == '?':
                    segments.append(Segment(text=f"{sentence}{punctuation}", next_pause=self.question_pause))
                elif punctuation == '\n':
                    segments.append(Segment(text=f"{sentence}{punctuation}.", next_pause=self.new_line_pause))
                else:
                    segments.append(Segment(text=f"{sentence}{punctuation}", next_pause=self.default_pause))
        last_sentence = sentences[-1].strip()
        if last_sentence:
            segments.append(Segment(text=f"{last_sentence}.", next_pause=self.default_pause))
        return segments
```
</details>

**Comment by mush42** [comment]
@thewh1teagle what class you're referring to?

**Comment by thewh1teagle** [comment]
Click on the details button at the end of the comment :)

**Comment by thewh1teagle** [comment]
I just created this repository with the new TTS model, there's some artifacts but even at this stage it's the best tts in Hebrew in terms of pronunciation and speed!

https://github.com/thewh1teagle/israwave

@mush42 
note of the project structure; it appears to simplify both training and inference processes. We might be able to enhance OptiSpeech by adopting a similar approach, such as using separate notebooks for each stage, separate gradio app into it's own project and folder etc.
