### ISSUE TITLE
restore epoch and step information when resuming training

### ISSUE THREAD

**Issue by thewh1teagle** [mush42/optispeech#5]
When resuming training from checkpoint it starts from 0 epoch and 0 step although it should be much higher and I can hear that it's already trained.
Can you fix it so it will restore it so I can keep track on the step counter when resuming?

https://github.com/Lightning-AI/pytorch-lightning/issues/12274

**Comment by thewh1teagle** [comment]
> occurring in --restore-from-checkpoint argument from the trainer?

Hey,
I don't see this argument in the trainer, maybe your'e talking about old version?

https://github.com/mush42/optispeech/blob/main/configs/train.yaml

**Comment by mush42** [comment]
@thewh1teagle
are you using the `forced_resume` argument?
I added this to be able to (re)load the model when I make changes to it's architecture while benefiting from already trained layers.
It is very niche use case, but I added it to save myself some time during development.

If you want to resume training normally, then the `ckpt_path` is all you need.
