### ISSUE TITLE
Why a demo optispeech-mike.mp4 has a coil whine sound in the right channel every so often?

### ISSUE THREAD

**Issue by AznamirWoW** [mush42/optispeech#8]
Curious

**Comment by mush42** [comment]
Maybe it is an artifact of MP4 conversion introduced by  `ffmpeg`?

**Comment by mush42** [comment]
Anyway the model is still training. This is an early sample. Let's wait until step 500K.

**Comment by thewh1teagle** [comment]
I have the same issue with the model I'm currently training. It's already the 500k step but theres many artifacts.

https://github.com/user-attachments/assets/24acad81-01b4-4c9d-8a1a-1645d41b8c0e

**Comment by mush42** [comment]
Maybe let it train for longer. I think more training is always better for removing these artifacts.

**Comment by mush42** [comment]
@thewh1teagle specially as you're training with a very small batch size, 4 I think. Small batch sizes always add noise to the gradients.

**Comment by thewh1teagle** [comment]
> specially as you're training with a very small batch size, 4 I think. Small batch sizes always add noise to the gradients.

Oh I didn't knew that. does few epochs of fine tune will fix it? So I can save computing time and only in the end fine tune a bit with larger batch size?

By the way, does the model can learn new things when fine tune? eg. there's some words that doesn't sound well so I'm considering to train a bit only on these words.
Also, does it possible to add more possible tokens some time? eg. say I want to add emotions for the sound in the future so the input text will be like:

`<happy>hello` or `<say/>hello` and I will train on new dataset with emotions sounds of the same speaker

**Comment by mush42** [comment]
@thewh1teagle 

1. Yes of course
2. Probably. But you should know the reason for misspronunciation first.
3. Maybe? You should try it. Although the model is designed for read-speech not emotional speech. For example, we use regression-based loss, and the model has no stochastic element at all.
